name: GrowMoneyServer

on:
  push:
    branches: [ "main" ]  # main 브랜치 푸시 시 자동 배포

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      name: Checkout source
            uses: actions/checkout@v3

      name: Set up JDK 21
            uses: actions/setup-java@v3
            with:
              java-version: '21'
              distribution: 'temurin'

      name: make application.properties
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.properties
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties

      name: Build with Gradle
            run: ./gradlew clean build -x test

      name: Copy jar to EC2
            uses: appleboy/scp-action@v0.1.4
            with:
              host: ${{ secrets.AWS_EC2_HOST }}
              username: ubuntu
              key: ${{ secrets.AWS_EC2_KEY }}
              source: "build/libs/*.jar"
              target: "/home/ubuntu/GrowMoney"


      name: Run Spring Boot on EC2
            uses: appleboy/ssh-action@v0.1.10
            with:
              host: ${{ secrets.AWS_EC2_HOST }}
              username: ubuntu
              key: ${{ secrets.AWS_EC2_KEY }}
              script: |
                cd ~/app# 기존 실행 중인 앱 종료
                PID=$(pgrep -f 'java -jar' || true)
                if [ -n "$PID" ]; then
                  echo "Killing existing process $PID"
                  kill -9 $PID
                fi
      
                  # 새 JAR 실행
                  nohup java -jar $(ls -t *.jar | head -n 1) > GrowMoney.log 2>&1 &
            echo "App started successfully!"
